### ISSUE TITLE
Better handling of 'new session' when the current session is a temporary session

### ISSUE THREAD

**Issue by bhostetler18** [bhostetler18/TuneCoach#16]
Could potentially append session numbers or give a popup

**Comment by jgravellefl** [comment]
I gave a popup to let you know that your session is created successfully. I want to wait until the session diagnostics window is finished to see if I need anything else

**Comment by jgravellefl** [comment]
I also changed the name of the temporary session in session diagnostics from "temporary session" to "new session", which I think is more clear and fully resolves the issue.
